{% set name = "napari-btrack-reader" %}
{% set version = "1.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-btrack-reader-{{ version }}.tar.gz
  sha256: 8d34a5d3c5a8b7d18b46f3059cceaa00da650b8d53e075ea0981217aaec7bcf1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools-scm
  run:
    - btrack >=0.4.0
    - napari-plugin-engine >=0.1.4
    - python >=3.6

test:
  imports:
    - napari_btrack_reader
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/quantumjot/napari-btrack-reader
  summary: A plugin to load btrack files
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
